### ISSUE TITLE
Mismatched types: expected `RawDocumentBuf`, found `Document`

### ISSUE THREAD

**Issue by clarkmcc** [mongodb/mongo-rust-driver#1363]
## Versions/Environment
1. What version of Rust are you using? 1.78
3. What operating system are you using? Ubuntu
4. What versions of the driver and its dependencies are you using? (Run `cargo pkgid mongodb` & `cargo pkgid bson`) git+https://github.com/mongodb/mongo-rust-driver?branch=main#mongodb@3.2.1, git+https://github.com/mongodb/bson-rust?branch=main#bson@2.13.0

## Describe the bug
Compile error when I try to build the library

```
error[E0308]: mismatched types
   --> /home/runner/.cargo/git/checkouts/mongo-rust-driver-b939e0128fabb835/f258c21/src/operation/bulk_write.rs:129:67
    |
129 | ...                   RunCommand::new(namespace.db.clone(), kill_cursors, None, None)?;
    |                       ---------------                       ^^^^^^^^^^^^ expected `RawDocumentBuf`, found `Document`
    |                       |
    |                       arguments to this function are incorrect
    |
note: associated function defined here
   --> /home/runner/.cargo/git/checkouts/mongo-rust-driver-b939e0128fabb835/f258c21/src/operation/run_command.rs:22:19
    |
22  |     pub(crate) fn new(
    |                   ^^^
23  |         db: String,
24  |         command: RawDocumentBuf,
    |         -----------------------

error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> /home/runner/.cargo/git/checkouts/mongo-rust-driver-b939e0128fabb835/f258c21/src/operation/bulk_write.rs:129:29
    |
129 | ...                   RunCommand::new(namespace.db.clone(), kill_cursors, None, None)?;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `operation::run_command::RunCommand<'_>`
    |
    = help: the trait `Try` is not implemented for `operation::run_command::RunCommand<'_>`
```

**BE SPECIFIC**:
* Did this issue arise out of nowhere, or after an update (of the driver,
server, and/or Rust)? Started today, probably after main branch was modified.

**Comment by clarkmcc** [comment]
Could this be caused by https://github.com/mongodb/mongo-rust-driver/pull/1356>

**Comment by isabelatkinson** [comment]
@clarkmcc which feature flags do you have enabled?

**Comment by clarkmcc** [comment]
@isabelatkinson 
```toml
bson = { git = "https://github.com/mongodb/bson-rust", branch = "main", features = [
    "chrono-0_4",
    "serde_with",
] }
mongodb = { git = "https://github.com/mongodb/mongo-rust-driver", branch = "main" }
```

**Comment by isabelatkinson** [comment]
Oh I see what happened. #1356 didn't pull in #1358 before it got merged, and those changes were incompatible. I'll get a PR up to fix this ASAP, but it might not get merged til next Monday when the rest of the team is back in. Thanks for reporting this!

**Comment by isabelatkinson** [comment]
#1364
